import Image from "next/image";
import Link from "next/link";
import {ServiceExplorer} from "@/components/shared/ServiceExplorer";
import {Journey} from "@/components/shared/Journey";

type HomeContent = {
  hero: {eyebrow:string; headlineLineOne:string; headlineLineTwo:string; description:string; primaryCta:string; secondaryCta:string};
  intro: {eyebrow:string; headlineLineOne:string; headlineLineTwo:string; bodyOne:string; bodyTwo:string; contextLink:string};
  whatWeDo: {eyebrow:string; headline:string; description:string; items:Array<{label:string; title:string; description:string}>};
  services: {eyebrow:string; headlineLineOne:string; headlineLineTwo:string; description:string; viewAll:string; items:Array<{summary:string; label:string; href:string; mediaSrc:string; mediaAlt:string; mediaPosition:string}>};
  journey: {eyebrow:string; headline:string; description:string; stages:Array<{title:string}>};
  network: {eyebrow:string; headline:string; description:string; viewNetwork:string; schedulesRoutes:string};
  why: {eyebrow:string; headline:string; description:string; pillars:Array<{title:string; description:string}>};
  trustedPartners: {eyebrow:string; headline:string; description:string; visitWebsite:string; partners:Array<{name:string; ownership:string; description:string; logoAlt:string; logoSrc:string; href:string}>};
  segments: {eyebrow:string; headline:string; items:Array<{title:string; description:string}>};
  digital: {eyebrow:string; headline:string; description:string; secondarySentence:string; capabilities:string[]};
  insights: {eyebrow:string; headline:string; description:string; links:Array<{label:string; href:string}>};
  finalCta: {eyebrow:string; headline:string; description:string; primaryCta:string; secondaryCta:string};
};


export function HomeExperience({locale, content}:{locale:"en"|"am"; content:HomeContent}) {
  const am = locale === "am";
  return <>
    <section className="home-intro section-white" aria-labelledby="home-intro-title"><div className="erl-container split-intro"><div><p className="eyebrow">{content.intro.eyebrow}</p><h2 id="home-intro-title" className="section-title">{content.intro.headlineLineOne}<br />{content.intro.headlineLineTwo}</h2></div><div className="section-copy"><p>{content.intro.bodyOne}</p><p>{content.intro.bodyTwo}</p><Link className="text-link" href={`/${locale}/services`}>{content.intro.contextLink} <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="home-what section-mint" aria-labelledby="home-what-title"><div className="erl-container"><div className="section-heading"><p className="eyebrow">{content.whatWeDo.eyebrow}</p><h2 id="home-what-title" className="section-title">{content.whatWeDo.headline}</h2><p className="section-copy">{content.whatWeDo.description}</p></div><Journey steps={content.whatWeDo.items}/></div></section>
    <section className="home-services section-white" aria-labelledby="home-services-title"><div className="erl-container"><div className="section-heading"><p className="eyebrow">{content.services.eyebrow}</p><h2 id="home-services-title" className="section-title">{content.services.headlineLineOne}<br />{content.services.headlineLineTwo}</h2><p className="section-copy">{content.services.description}</p></div><ServiceExplorer items={content.services.items} locale={locale}/><div className="button-row centered"><Link className="erl-button secondary" href={`/${locale}/services`}>{content.services.viewAll} <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="home-multimodal section-cyan" aria-labelledby="home-journey-title"><div className="erl-container"><div className="section-heading"><p className="eyebrow">{content.journey.eyebrow}</p><h2 id="home-journey-title" className="section-title">{content.journey.headline}</h2><p className="section-copy">{content.journey.description}</p></div><Journey steps={content.journey.stages} compact/></div></section>
    <section className="home-corridor section-bluegreen" aria-labelledby="home-network-title"><div className="erl-container corridor-layout"><div><p className="eyebrow">{content.network.eyebrow}</p><h2 id="home-network-title" className="section-title">{content.network.headline}</h2><p className="section-copy">{content.network.description}</p><div className="button-row"><Link className="erl-button" href={`/${locale}/network/ethiopia-djibouti-corridor`}>{content.network.viewNetwork} <span aria-hidden="true">→</span></Link><Link className="erl-button secondary" href={`/${locale}/network/schedules-routes`}>{content.network.schedulesRoutes}</Link></div></div><div className="corridor-map"><Image src="/media/images/maps/ethio-djibouti-corridor-map.png" alt={am?"የኢትዮጵያ–ጅቡቲ የሎጂስቲክስ ኮሪደር ካርታ":"Ethiopia–Djibouti logistics corridor map"} fill sizes="(max-width: 900px) 100vw, 50vw" /></div></div></section>
    <section className="home-why section-white" aria-labelledby="home-why-title"><div className="erl-container"><div className="section-heading"><p className="eyebrow">{content.why.eyebrow}</p><h2 id="home-why-title" className="section-title">{content.why.headline}</h2><p className="section-copy">{content.why.description}</p></div><div className="pillar-grid">{content.why.pillars.map((pillar,i)=><article key={pillar.title}><span className="eyebrow">{String(i+1).padStart(2,"0")}</span><h3>{pillar.title}</h3><p>{pillar.description}</p></article>)}</div></div></section>
    <section className="home-shareholders section-mint" aria-labelledby="home-shareholders-title"><div className="erl-container"><div className="section-heading"><p className="eyebrow">{content.trustedPartners.eyebrow}</p><h2 id="home-shareholders-title" className="section-title">{content.trustedPartners.headline}</h2><p className="section-copy">{content.trustedPartners.description}</p></div><div className="partner-grid">{content.trustedPartners.partners.map((partner)=><article key={partner.name} className="partner-card"><Image src={partner.logoSrc} alt={partner.logoAlt} width={180} height={80} /><p className="ownership">{partner.ownership.match(/\d+\s*%/)?.[0]}</p><span className="eyebrow">{partner.ownership}</span><h3>{partner.name}</h3><p>{partner.description}</p><a className="text-link" href={partner.href} target="_blank" rel="noreferrer">{content.trustedPartners.visitWebsite}</a></article>)}</div></div></section>
    <section className="home-segments section-neutral" aria-labelledby="home-segments-title"><div className="erl-container"><p className="eyebrow">{content.segments.eyebrow}</p><h2 id="home-segments-title" className="section-title">{content.segments.headline}</h2><div className="segment-grid">{content.segments.items.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.description}</p></article>)}</div></div></section>
    <section className="home-digital section-cyan" aria-labelledby="home-digital-title"><div className="erl-container digital-panel"><div><p className="eyebrow">{content.digital.eyebrow}</p><h2 id="home-digital-title" className="section-title">{content.digital.headline}</h2><p className="section-copy">{content.digital.description}</p><p className="development-note">{content.digital.secondarySentence}</p><Link className="erl-button" href={`/${locale}/digital-logistics#future-portal`}>{am ? "ተጨማሪ" : "View future portal"} <span aria-hidden="true">→</span></Link></div><ul className="capability-list">{content.digital.capabilities.map(item=><li key={item}>{item}<span aria-hidden="true">+</span></li>)}</ul></div></section>
    <section className="home-insights section-white" aria-labelledby="home-insights-title"><div className="erl-container"><p className="eyebrow">{content.insights.eyebrow}</p><h2 id="home-insights-title" className="section-title">{content.insights.headline}</h2><p className="section-copy">{content.insights.description}</p><div className="insight-links">{content.insights.links.map((link,i)=><Link key={link.href} href={`/${locale}${link.href}`}><span className="eyebrow">{String(i+1).padStart(2,"0")}</span>{link.label}<span aria-hidden="true">↗</span></Link>)}</div></div></section>
    <section className="home-final section-green" aria-labelledby="home-final-title"><div className="erl-container final-panel"><p className="eyebrow">{content.finalCta.eyebrow}</p><h2 id="home-final-title" className="section-title">{content.finalCta.headline}</h2><p className="section-copy">{content.finalCta.description}</p><div className="button-row"><Link className="erl-button" href={`/${locale}/quote`}>{content.finalCta.primaryCta} <span aria-hidden="true">↗</span></Link><Link className="erl-button secondary" href={`/${locale}/contact`}>{content.finalCta.secondaryCta}</Link></div></div></section>
  </>;
}
