import type {CareerInsightsContent} from "./CareerInsightsPage";

const railImage = "/media/images/rail/ethiopia/ethiopian-railway-locomotive-01.jpg";
const mapImage = "/media/images/maps/ethio-djibouti-corridor-map.png";

const enCareers: CareerInsightsContent = {metadata: {title: "Careers | EthioRail Logistics", description: "Explore future opportunities connected to logistics, transport, operations, and digital systems at EthioRail."}, hero: {eyebrow: "CAREERS", title: "Move your career forward.", description: "Contribute to the logistics, transport, operations, technology, and connected movement conversations shaping the corridor.", image: railImage, imageAlt: "Ethiopian railway locomotive on a freight route."}, intro: {eyebrow: "WORK WITH THE JOURNEY", title: "Careers connected to practical movement.", paragraphs: ["EthioRail’s work sits across the handoffs that help cargo move: inland logistics, rail, road, ports, documentation, and service coordination.", "This page will share verified opportunities when they are approved. It does not represent current vacancies or promise roles in any particular area."]}, feature: {eyebrow: "AREAS OF WORK", title: "Broad functions across connected logistics.", items: ["Logistics & Operations", "Rail & Transport Coordination", "Freight & Commercial Services", "Warehousing & Inland Logistics", "Finance & Administration", "Technology & Digital Systems", "Customer Service", "Corporate Functions"].map((title) => ({title, description: "A broad functional area that may support connected logistics work when verified roles are available."}))}, status: {eyebrow: "CURRENT OPPORTUNITIES", title: "No verified vacancies are published yet.", description: "Current opportunities will be published here when verified vacancies are available.", action: {label: "Contact EthioRail", href: "/contact"}}, related: {eyebrow: "LEARN ABOUT ETHIORAIL", title: "Understand the organization and the route behind the work.", links: [{label: "About EthioRail", href: "/about"}, {label: "Services", href: "/services"}, {label: "Network", href: "/network"}]}, cta: {eyebrow: "START A CONVERSATION", title: "Have a question about future opportunities?", description: "Use the contact page for a general inquiry. Formal career details will appear when approved information is available.", primary: "Contact Logistics", secondary: "Explore Insights"}};
const enInsights: CareerInsightsContent = {metadata: {title: "Insights | EthioRail Logistics", description: "Explore future EthioRail updates, network information, logistics resources, and announcements."}, hero: {eyebrow: "INSIGHTS", title: "Updates from the journey ahead.", description: "A future home for verified company updates, network information, logistics resources, and announcements.", image: mapImage, imageAlt: "Ethiopia–Djibouti corridor map showing the route toward global markets."}, intro: {eyebrow: "THE ROAD AHEAD", title: "Useful context for connected movement.", paragraphs: ["Insights will bring together the information that helps customers, partners, and the wider logistics community understand the route and the work around it.", "No articles or downloadable resources are published yet. Content will appear here once it has been reviewed and approved."]}, status: {eyebrow: "INSIGHTS LIBRARY", title: "Choose a section to explore.", description: "Visit News & Updates for future company announcements, or Resources for future service and network information.", action: {label: "Explore News & Updates", href: "/insights/news"}}, related: {eyebrow: "INSIGHTS SECTIONS", title: "Explore the future content structure.", links: [{label: "News & Updates", href: "/insights/news"}, {label: "Resources", href: "/insights/resources"}, {label: "Network", href: "/network"}]}, cta: {eyebrow: "NEED ROUTE CONTEXT?", title: "Start with the services and network.", description: "Explore the operating context while the Insights library is being prepared.", primary: "Explore Network", secondary: "Contact Logistics"}};
const enNews: CareerInsightsContent = {...enInsights, metadata: {title: "News & Updates | EthioRail Logistics", description: "Verified EthioRail news and announcements will be published here."}, hero: {...enInsights.hero, eyebrow: "NEWS & UPDATES", title: "Verified updates when they are ready.", description: "A clear place for future EthioRail announcements, company news, and approved updates."}, intro: {eyebrow: "NEWSROOM", title: "No unverified stories.", paragraphs: ["This page is reserved for verified EthioRail news and announcements.", "There are no published articles yet, so no dates, partnerships, project announcements, or executive quotes are presented here."]}, status: {eyebrow: "CURRENT NEWS", title: "Verified EthioRail news and announcements will appear here.", description: "The future article system is ready for reviewed content, with room for titles, dates, categories, descriptions, images, and future article links."}, related: {...enInsights.related, title: "Continue exploring EthioRail context."}, cta: {...enInsights.cta, primary: "Explore Services"}};
const enResources: CareerInsightsContent = {...enInsights, metadata: {title: "Resources | EthioRail Logistics", description: "Future EthioRail service guides, network information, shipping resources, and customer documents."}, hero: {...enInsights.hero, eyebrow: "RESOURCES", title: "Practical information for the route.", description: "A future home for approved service guides, network information, shipping resources, forms, and customer information."}, intro: {eyebrow: "RESOURCE LIBRARY", title: "Useful information, published carefully.", paragraphs: ["Resources will help make the connected logistics journey easier to understand and prepare for.", "No downloadable PDFs, forms, or customer documents are published yet."]}, status: {eyebrow: "CURRENT RESOURCES", title: "Resources will be published when approved.", description: "Future categories may include Service Guides, Network Information, Shipping Resources, Forms & Documents, and Customer Information."}, related: {...enInsights.related, title: "Explore the route before the library grows."}, cta: {...enInsights.cta, primary: "Explore Services"}};

const amCareers: CareerInsightsContent = {...enCareers, metadata: {title: "ስራዎች | ኢትዮ ሬይል ሎጂስቲክስ", description: "ከሎጂስቲክስ፣ መጓጓዣ፣ ኦፕሬሽን እና ዲጂታል ስርዓቶች ጋር የተገናኙ የወደፊት እድሎችን ይመልከቱ።"}, hero: {...enCareers.hero, eyebrow: "ስራዎች", title: "ሙያዎን ወደፊት ያንቀሳቅሱ።", description: "በኮሪደሩ የሚመራውን ሎጂስቲክስ፣ መጓጓዣ፣ ኦፕሬሽን እና ዲጂታል ስርዓት ስራ ይቀላቀሉ።"}, intro: {eyebrow: "ከጉዞው ጋር ይስሩ", title: "ከተግባራዊ እንቅስቃሴ ጋር የተገናኙ ስራዎች።", paragraphs: ["የኢትዮ ሬይል ስራ በውስጥ ሎጂስቲክስ፣ ባቡር፣ መንገድ፣ ወደብ እና ማስተባበሪያ ዙሪያ ይገኛል።", "የተረጋገጡ እድሎች ሲኖሩ በዚህ ገጽ ይታተማሉ።"]}, feature: {...enCareers.feature!, eyebrow: "የስራ መስኮች", title: "በተገናኘ ሎጂስቲክስ ውስጥ ሰፊ የስራ መስኮች።", items: enCareers.feature!.items.map((item) => ({title: item.title, description: "የተረጋገጡ የስራ እድሎች ሲኖሩ ሊደግፍ የሚችል የስራ መስክ።"}))}, status: {eyebrow: "የአሁኑ እድሎች", title: "እስካሁን የተረጋገጠ ክፍት የስራ ቦታ የለም።", description: "የተረጋገጡ ክፍት የስራ ቦታዎች ሲኖሩ እዚህ ይታተማሉ።", action: {label: "ኢትዮ ሬይልን ያግኙ", href: "/contact"}}};
const amInsights: CareerInsightsContent = {...enInsights, metadata: {title: "ግንዛቤዎች | ኢትዮ ሬይል ሎጂስቲክስ", description: "የወደፊት የኢትዮ ሬይል ዜናዎችን፣ የኔትወርክ መረጃዎችን እና የሎጂስቲክስ ምንጮችን ይመልከቱ።"}, hero: {...enInsights.hero, eyebrow: "ግንዛቤዎች", title: "ከፊት ስላለው ጉዞ የሚመጡ ዝመናዎች።", description: "ለወደፊት የኩባንያ ዝመናዎች፣ የኔትወርክ መረጃ እና የሎጂስቲክስ ምንጮች ቦታ።"}, intro: {eyebrow: "የፊት መንገድ", title: "ለተገናኘ እንቅስቃሴ ጠቃሚ አውድ።", paragraphs: ["ግንዛቤዎች ደንበኞች እና አጋሮች መንገዱን እና ስራውን እንዲረዱ ይረዳል።", "ጽሑፎች እና የሚወርዱ ምንጮች ገና አልታተሙም።"]}, status: {eyebrow: "የግንዛቤ ቤተ-መጽሐፍት", title: "ለመመልከት አንድ ክፍል ይምረጡ።", description: "ለወደፊት የኩባንያ ዜናዎች ዜና እና ዝመናዎችን፣ ወይም ለአገልግሎት መረጃ ምንጮችን ይመልከቱ።", action: {label: "ዜና እና ዝመናዎች", href: "/insights/news"}}};
const amNews: CareerInsightsContent = {...amInsights, metadata: {title: "ዜና እና ዝመናዎች | ኢትዮ ሬይል ሎጂስቲክስ", description: "የተረጋገጡ የኢትዮ ሬይል ዜናዎች እና ማስታወቂያዎች እዚህ ይታተማሉ።"}, hero: {...amInsights.hero, eyebrow: "ዜና እና ዝመናዎች", title: "የተረጋገጡ ዝመናዎች ሲዘጋጁ።"}, status: {eyebrow: "የአሁኑ ዜና", title: "የተረጋገጡ ዜናዎች እዚህ ይታተማሉ።", description: "የወደፊት የጽሑፍ መዋቅር ለርዕስ፣ ቀን፣ ምድብ እና መግለጫ ዝግጁ ነው።"}};
const amResources: CareerInsightsContent = {...amInsights, metadata: {title: "ምንጮች | ኢትዮ ሬይል ሎጂስቲክስ", description: "የወደፊት የኢትዮ ሬይል አገልግሎት መመሪያዎች፣ የኔትወርክ መረጃ እና የደንበኛ ሰነዶች።"}, hero: {...amInsights.hero, eyebrow: "ምንጮች", title: "ለመንገዱ ተግባራዊ መረጃ።"}, status: {eyebrow: "የአሁኑ ምንጮች", title: "ምንጮች ሲፀድቁ ይታተማሉ።", description: "የወደፊት ምድቦች የአገልግሎት መመሪያዎችን፣ የኔትወርክ መረጃን እና የደንበኛ መረጃን ሊያካትቱ ይችላሉ።"}};

amCareers.related = {eyebrow: "ኢትዮ ሬይልን ይረዱ", title: "ድርጅቱን እና የስራውን መንገድ ይመልከቱ።", links: [{label: "ስለ ኢትዮ ሬይል", href: "/about"}, {label: "አገልግሎቶች", href: "/services"}, {label: "ኔትወርክ", href: "/network"}]};
amCareers.cta = {eyebrow: "ውይይት ይጀምሩ", title: "ስለ ወደፊት እድሎች ጥያቄ አለዎት?", description: "የተረጋገጠ መረጃ እስኪታተም ድረስ ለአጠቃላይ ጥያቄ የመገናኛ ገጹን ይጠቀሙ።", primary: "ሎጂስቲክስን ያግኙ", secondary: "ግንዛቤዎችን ይመልከቱ"};
amInsights.related = {eyebrow: "የግንዛቤ ክፍሎች", title: "የወደፊት የይዘት መዋቅርን ይመልከቱ።", links: [{label: "ዜና እና ዝመናዎች", href: "/insights/news"}, {label: "ምንጮች", href: "/insights/resources"}, {label: "ኔትወርክ", href: "/network"}]};
amInsights.cta = {eyebrow: "የመንገድ አውድ ያስፈልግዎታል?", title: "በአገልግሎቶች እና ኔትወርክ ይጀምሩ።", description: "የግንዛቤ ቤተ-መጽሐፍት እየተዘጋጀ ሳለ የስራውን አውድ ይመልከቱ።", primary: "ኔትወርክን ይመልከቱ", secondary: "ሎጂስቲክስን ያግኙ"};
amNews.related = amInsights.related; amNews.cta = amInsights.cta;
amResources.related = amInsights.related; amResources.cta = amInsights.cta;export const careerInsightsContent = {en: {careers: enCareers, insights: enInsights, news: enNews, resources: enResources}, am: {careers: amCareers, insights: amInsights, news: amNews, resources: amResources}};
