"use client";

import {useState, type FormEvent} from "react";
import {z} from "zod";

export type InquiryFormCopy = {
  fields: Record<string, {label: string; placeholder: string}>;
  inquiryOptions?: Array<{value: string; label: string}>;
  serviceOptions?: Array<{value: string; label: string}>;
  submit: string;
  pending: string;
  required: string;
  invalidEmail: string;
  chooseOne: string;
};

const contactSchema = z.object({fullName: z.string().trim().min(2), company: z.string().trim().min(2), email: z.string().email(), phone: z.string().trim().min(5), inquiryType: z.string().min(1), message: z.string().trim().min(10)});
const quoteSchema = contactSchema.extend({origin: z.string().trim().min(2), destination: z.string().trim().min(2), cargoType: z.string().trim().min(2), weight: z.string().min(1), volume: z.string().min(1), packageCount: z.string().min(1), services: z.array(z.string()).min(1), timing: z.string().trim().min(2)});

export function InquiryForm({kind, copy}: {kind: "contact" | "quote"; copy: InquiryFormCopy}) {
  const [values, setValues] = useState<Record<string, string | string[]>>({services: []});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [notice, setNotice] = useState("");
  const update = (name: string, value: string | string[]) => { setValues((current) => ({...current, [name]: value})); setErrors((current) => ({...current, [name]: ""})); setNotice(""); };
  const field = (name: string, type = "text") => { const item = copy.fields[name]; const error = errors[name]; return <div key={name}><label htmlFor={name} className="mb-2 block text-sm font-semibold">{item.label}</label>{name === "message" ? <textarea id={name} rows={5} placeholder={item.placeholder} value={String(values[name] ?? "")} onChange={(event) => update(name, event.target.value)} className="min-h-32 w-full resize-y rounded-sm border border-rail-ink/16 bg-white/65 px-4 py-3 outline-none focus:border-ethiorail-green focus:ring-2 focus:ring-ethiorail-green/20" aria-invalid={Boolean(error)} /> : <input id={name} type={type} placeholder={item.placeholder} value={String(values[name] ?? "")} onChange={(event) => update(name, event.target.value)} className="min-h-12 w-full rounded-sm border border-rail-ink/16 bg-white/65 px-4 py-3 outline-none focus:border-ethiorail-green focus:ring-2 focus:ring-ethiorail-green/20" aria-invalid={Boolean(error)} />}{error ? <p className="mt-1 text-sm font-semibold text-red-700" role="alert">{error}</p> : null}</div>; };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const result = (kind === "contact" ? contactSchema : quoteSchema).safeParse(values); if (!result.success) { const next: Record<string, string> = {}; result.error.issues.forEach((issue) => { const key = String(issue.path[0]); next[key] = key === "email" ? copy.invalidEmail : key === "inquiryType" || key === "services" ? copy.chooseOne : copy.required; }); setErrors(next); return; } setErrors({}); setNotice(copy.pending); };
  const names = kind === "contact" ? ["fullName", "company", "email", "phone", "inquiryType", "message"] : ["fullName", "company", "email", "phone", "origin", "destination", "cargoType", "weight", "volume", "packageCount", "timing", "message"];
  return <form onSubmit={submit} noValidate className="border-t border-ethiorail-deep-green/25 pt-7"><div className="grid gap-5 md:grid-cols-2">{names.map((name) => name === "message" ? <div key={name} className="md:col-span-2">{field(name)}</div> : name === "inquiryType" ? <div key={name}><label htmlFor={name} className="mb-2 block text-sm font-semibold">{copy.fields[name].label}</label><select id={name} value={String(values[name] ?? "")} onChange={(event) => update(name, event.target.value)} className="min-h-12 w-full rounded-sm border border-rail-ink/16 bg-white/65 px-4 py-3 outline-none focus:border-ethiorail-green" aria-invalid={Boolean(errors[name])}><option value="">{copy.fields[name].placeholder}</option>{copy.inquiryOptions?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{errors[name] ? <p className="mt-1 text-sm font-semibold text-red-700" role="alert">{errors[name]}</p> : null}</div> : field(name, name === "email" ? "email" : name === "phone" ? "tel" : "text") )}</div>{kind === "quote" ? <fieldset className="mt-7"><legend className="mb-3 text-sm font-semibold">{copy.fields.services.label}</legend><div className="grid gap-2 sm:grid-cols-2">{copy.serviceOptions?.map((option) => { const checked = Array.isArray(values.services) && values.services.includes(option.value); return <label key={option.value} className={`flex min-h-12 cursor-pointer items-center gap-3 border px-4 py-3 text-sm font-semibold ${checked ? "border-ethiorail-green bg-ethiorail-green/10" : "border-rail-ink/12 bg-white/45"}`}><input type="checkbox" checked={checked} onChange={() => { const selected = Array.isArray(values.services) ? values.services : []; update("services", checked ? selected.filter((item) => item !== option.value) : [...selected, option.value]); }} className="h-4 w-4 accent-ethiorail-green" />{option.label}</label>; })}</div>{errors.services ? <p className="mt-2 text-sm font-semibold text-red-700" role="alert">{errors.services}</p> : null}</fieldset> : null}<div className="mt-7 flex flex-col gap-4 sm:flex-row sm:items-center"><button type="submit" className="inline-flex min-h-12 items-center justify-center rounded-sm border border-ethiorail-green bg-ethiorail-green px-6 py-3 font-semibold text-cool-canvas hover:border-ethiorail-bright-green hover:bg-ethiorail-bright-green focus:outline-none focus:ring-2 focus:ring-ethiorail-green/30">{copy.submit} <span aria-hidden="true" className="ml-2">→</span></button><p className="text-sm leading-6 text-secondary-text">{copy.pending}</p></div>{notice ? <p className="mt-6 border-l-2 border-ethiorail-green bg-ethiorail-green/10 px-4 py-3 text-sm font-semibold" role="status" aria-live="polite">{notice}</p> : null}</form>;
}
